import { StyleSheet, Platform } from 'react-native';

const ACCENT_COLOR = '#2563eb'; // Blue accent for professional look
const GRADIENT_BG = ['#f8fafc', '#e0e7ef'];

export const voiceAnalyticsStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: 'linear-gradient(135deg, #f8fafc 0%, #e0e7ef 100%)',
        padding: 0,
    },
    scrollContainer: {
        flex: 1,
    },
    scrollContent: {
        flexGrow: 1,
    },
    headerBar: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 24,
        paddingTop: 24,
        paddingBottom: 16,
        backgroundColor: '#fff',
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
        zIndex: 10,
    },
    appTitle: {
        fontSize: 24,
        fontWeight: '700',
        color: ACCENT_COLOR,
        letterSpacing: 1,
    },
    userAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: ACCENT_COLOR,
        alignItems: 'center',
        justifyContent: 'center',
    },
    userAvatarText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 18,
    },
    mainContent: {
        flex: 1,
    },
    leftColumn: {
        marginBottom: 16,
    },
    statusCard: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 36,
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.10,
        shadowRadius: 12,
        elevation: 6,
    },
    liveBadge: {
        position: 'absolute',
        top: 16,
        right: 16,
        backgroundColor: '#ef4444',
        borderRadius: 12,
        paddingVertical: 4,
        paddingHorizontal: 12,
        shadowColor: '#ef4444',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.2,
        shadowRadius: 4,
    },
    liveText: {
        color: '#fff',
        fontWeight: 'bold',
        fontSize: 12,
        letterSpacing: 1,
    },
    primaryButton: {
        backgroundColor: ACCENT_COLOR,
        borderRadius: 10,
        paddingVertical: 16,
        paddingHorizontal: 32,
        marginTop: 24,
        minWidth: 180,
        alignItems: 'center',
        shadowColor: ACCENT_COLOR,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.12,
        shadowRadius: 6,
    },
    primaryButtonText: {
        color: '#fff',
        fontWeight: '700',
        fontSize: 18,
        letterSpacing: 0.5,
    },
    speakerStatus: {
        color: '#1e293b',
        fontWeight: '600',
        fontSize: 20,
        marginBottom: 18,
        textAlign: 'center',
    },
    button: {
        minHeight: 44,
        minWidth: 44,
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 8,
        backgroundColor: ACCENT_COLOR,
        marginVertical: 8,
    },
    buttonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    metricsContainer: {
        ...Platform.select({
            web: {
                flexDirection: 'row',
                alignItems: 'flex-start',
                justifyContent: 'space-between',
                gap: 20,
            },
            default: {
                flexDirection: 'column',
                gap: 16,
            },
        }),
    },
    metricsContainerNarrow: {
        flexDirection: 'column',
        gap: 16,
    },
    metricsGrid: {
        ...Platform.select({
            web: {
                flexDirection: 'row',
                gap: 16,
                flex: 1,
            },
            default: {
                flexDirection: 'column',
                gap: 16,
                width: '100%',
            },
        }),
    },
    metricsGridNarrow: {
        flexDirection: 'column',
        gap: 16,
        width: '100%',
    },
    legendWrapper: {
        ...Platform.select({
            web: {
                marginLeft: 16,
                maxWidth: 300,
            },
            default: {
                marginTop: 8,
                marginBottom: 16,
                alignSelf: 'center',
                width: '100%',
                maxWidth: 400,
            },
        }),
    },
    legendWrapperNarrow: {
        marginLeft: 0,
        marginTop: 16,
        width: '100%',
        maxWidth: undefined,
    },
    metricCard: {
        flex: 1,
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 24,
        minHeight: 120,
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 1 },
                shadowOpacity: 0.1,
                shadowRadius: 2,
            },
            android: {
                elevation: 2,
            },
        }),
    },
    metricCardNarrow: {
        flex: 0,
        marginBottom: 12,
    },
    metricLabel: {
        color: '#64748b',
        fontSize: 14,
        marginBottom: 8,
    },
    metricValue: {
        color: '#1e293b',
        fontSize: 24,
        fontWeight: '600',
    },
    transcriptContainer: {
        flex: 1,
        backgroundColor: 'white',
        borderRadius: 16,
        padding: 24,
        marginTop: 16,
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 1 },
                shadowOpacity: 0.1,
                shadowRadius: 2,
            },
            android: {
                elevation: 2,
            },
        }),
    },
    transcriptTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1e293b',
        marginBottom: 8,
    },
    collapseHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        marginBottom: 8,
    },
    collapseHeaderText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#475569',
    },
    collapseIcon: {
        fontSize: 16,
        color: '#475569',
    },
    activeSpeakersContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginBottom: 16,
    },
    activeSpeakerChip: {
        backgroundColor: '#f1f5f9',
        borderRadius: 16,
        paddingVertical: 8,
        paddingHorizontal: 16,
        marginRight: 8,
        marginBottom: 8,
    },
    activeSpeakerText: {
        color: '#475569',
        fontSize: 14,
        fontWeight: '500',
    },
    transcriptsList: {
        flex: 1,
    },
    transcriptItem: {
        flexDirection: 'row',
        alignItems: 'flex-end',
        marginBottom: 18,
    },
    transcriptBubble: {
        maxWidth: '80%',
        padding: 16,
        borderRadius: 18,
        backgroundColor: '#e0e7ef',
        marginHorizontal: 8,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.06,
        shadowRadius: 4,
    },
    transcriptBubbleRight: {
        backgroundColor: ACCENT_COLOR,
        alignSelf: 'flex-end',
    },
    transcriptText: {
        color: '#1e293b',
        fontSize: 16,
    },
    transcriptTextRight: {
        color: '#fff',
    },
    timestamp: {
        fontSize: 12,
        color: '#64748b',
        marginTop: 4,
        marginLeft: 8,
    },
    audioIndicator: {
        marginTop: 8,
        width: '100%',
    },
    audioLabelContainer: {
        marginBottom: 5,
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        ...Platform.select({
            web: {
                flexDirection: 'row',
            },
            default: {
                flexDirection: 'column',
            }
        }),
    },
    audioLabel: {
        color: '#475569',
        fontSize: 14,
        flexWrap: 'wrap',
    },
    audioLabelSmall: {
        color: '#64748b',
        fontSize: 12,
        marginTop: 2,
    },
    audioBar: {
        height: 18,
        borderRadius: 9,
        backgroundColor: '#e0e7ef',
        overflow: 'hidden',
        marginTop: 8,
        marginBottom: 8,
        position: 'relative',
    },
    audioLevel: {
        height: '100%',
        borderRadius: 9,
        backgroundColor: ACCENT_COLOR,
        position: 'absolute',
        left: 0,
        top: 0,
        // width should be set dynamically in the component
    },
    baselineMark: {
        position: 'absolute',
        top: 0,
        bottom: 0,
        width: 2,
        backgroundColor: '#94a3b8',
        opacity: 0.8,
        zIndex: 2,
    },
    baselineArea: {
        position: 'absolute',
        height: '100%',
        backgroundColor: '#e2e8f0',
        opacity: 0.5,
        left: 0,
    },
    legendContainer: {
        backgroundColor: 'white',
        borderRadius: 12,
        padding: 12,
        ...Platform.select({
            web: {
                width: 250,
            },
            default: {
                width: '100%',
            },
        }),
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 2 },
                shadowOpacity: 0.1,
                shadowRadius: 4,
            },
            android: {
                elevation: 3,
            },
        }),
    },
    legendTitle: {
        fontSize: 14,
        fontWeight: '600',
        color: '#1e293b',
        marginBottom: 10,
        textAlign: 'center',
    },
    legendDescription: {
        fontSize: 12,
        color: '#64748b',
        marginBottom: 16,
        textAlign: 'center',
    },
    soundLevelBar: {
        marginBottom: 16,
    },
    soundLevelGradient: {
        height: 16,
        borderRadius: 8,
        flexDirection: 'row',
        overflow: 'hidden',
        marginBottom: 2,
    },
    soundLevelSegment: {
        flex: 1,
        height: '100%',
    },
    tickMarksContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingHorizontal: 0,
        height: 6,
    },
    tickMark: {
        width: 1,
        height: 6,
        backgroundColor: '#64748b',
    },
    soundLevelLabels: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 4,
    },
    soundLevelLabel: {
        fontSize: 9,
        color: '#64748b',
    },
    legendItems: {
        gap: 4,
        marginTop: 8,
    },
    legendItem: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 3,
    },
    legendColor: {
        width: 12,
        height: 12,
        borderRadius: 3,
        marginRight: 6,
    },
    legendText: {
        color: '#475569',
        fontSize: 11,
    },
    errorContainer: {
        backgroundColor: '#fee2e2',
        padding: 12,
        borderRadius: 8,
        marginBottom: 16,
        width: '100%',
    },
    errorText: {
        color: '#b91c1c',
        fontSize: 14,
    },
    buttonDisabled: {
        opacity: 0.5,
    },
    // Modal styles
    modalOverlay: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: 'rgba(0,0,0,0.5)',
    },
    modalContent: {
        backgroundColor: '#fff',
        borderRadius: 18,
        padding: 32,
        width: '90%',
        maxWidth: 420,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.18,
        shadowRadius: 12,
        elevation: 8,
        position: 'relative',
    },
    modalTitle: {
        fontSize: 20,
        fontWeight: 'bold',
        marginBottom: 12,
        textAlign: 'center',
        color: '#1e293b',
    },
    modalDescription: {
        fontSize: 16,
        marginBottom: 20,
        textAlign: 'center',
        color: '#4b5563',
    },
    modalCloseButton: {
        position: 'absolute',
        top: 16,
        right: 16,
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#e0e7ef',
        alignItems: 'center',
        justifyContent: 'center',
    },
    modalCloseIcon: {
        fontSize: 20,
        color: ACCENT_COLOR,
    },
    nameInput: {
        borderWidth: 2,
        borderColor: ACCENT_COLOR,
        borderRadius: 10,
        padding: 14,
        fontSize: 18,
        marginBottom: 24,
        backgroundColor: '#f8fafc',
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
    },
    modalButton: {
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderRadius: 8,
        minWidth: 120,
        alignItems: 'center',
    },
    skipButton: {
        backgroundColor: '#f3f4f6',
    },
    skipButtonText: {
        color: '#6b7280',
        fontSize: 16,
        fontWeight: '500',
    },
    submitButton: {
        backgroundColor: '#22c55e',
    },
    submitButtonText: {
        color: 'white',
        fontSize: 16,
        fontWeight: '500',
    },
    // User info styles
    userInfo: {
        marginBottom: 15,
        alignItems: 'center',
        flexDirection: 'row',
        justifyContent: 'space-between',
        width: '100%',
    },
    welcomeText: {
        fontSize: 16,
        fontWeight: '500',
        color: '#1f2937',
    },
    signOutButton: {
        backgroundColor: '#f3f4f6',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 6,
        borderWidth: 1,
        borderColor: '#d1d5db',
    },
    signOutText: {
        fontSize: 14,
        color: '#6b7280',
        fontWeight: '500',
    },
    // Add new styles for MongoDB save status
    saveStatusContainer: {
        padding: 12,
        borderRadius: 8,
        marginBottom: 16,
        width: '100%',
    },
    saveStatusText: {
        fontSize: 14,
        textAlign: 'center',
    },
    // Add new styles for hamburger menu and sidebar
    hamburgerButton: {
        position: 'absolute',
        top: 16,
        left: 16,
        zIndex: 1000,
        padding: 8,
        backgroundColor: 'white',
        borderRadius: 8,
        ...Platform.select({
            ios: {
                shadowColor: '#000',
                shadowOffset: { width: 0, height: 1 },
                shadowOpacity: 0.1,
                shadowRadius: 2,
            },
            android: {
                elevation: 2,
            },
        }),
    },
    hamburgerIcon: {
        fontSize: 24,
        color: '#475569',
    },
    sidebar: {
        position: 'absolute',
        top: 0,
        left: 0,
        bottom: 0,
        width: 320,
        backgroundColor: 'rgba(255,255,255,0.95)',
        zIndex: 1001,
        backdropFilter: 'blur(12px)',
        shadowColor: '#000',
        shadowOffset: { width: 2, height: 0 },
        shadowOpacity: 0.18,
        shadowRadius: 8,
        elevation: 10,
        ...Platform.select({
            web: {
                overflowY: 'auto',
            },
        }),
    },
    sidebarHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    sidebarTitleContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
    },
    sidebarTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: ACCENT_COLOR,
    },
    downloadButton: {
        padding: 10,
        backgroundColor: ACCENT_COLOR,
        borderRadius: 8,
    },
    downloadButtonText: {
        color: '#fff',
        fontWeight: '600',
        fontSize: 16,
    },
    closeButton: {
        padding: 8,
    },
    closeButtonText: {
        fontSize: 24,
        color: '#64748b',
    },
    sidebarContent: {
        flex: 1,
        padding: 16,
    },
    historyItem: {
        padding: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    historyItemHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginBottom: 8,
    },
    historyDate: {
        fontSize: 14,
        color: '#6b7280',
        fontWeight: '500',
    },
    historyTime: {
        fontSize: 14,
        color: '#6b7280',
    },
    historyContent: {
        marginTop: 4,
    },
    historySpeaker: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1f2937',
        marginBottom: 4,
    },
    historyText: {
        fontSize: 15,
        color: '#374151',
        lineHeight: 22,
    },
    historyDivider: {
        height: 1,
        backgroundColor: '#e5e7eb',
        marginVertical: 8,
    },
    conversationGroup: {
        marginBottom: 24,
        backgroundColor: '#f8fafc',
        borderRadius: 12,
        padding: 16,
    },
    conversationDate: {
        fontSize: 16,
        fontWeight: '600',
        color: '#1e293b',
        marginBottom: 12,
        paddingBottom: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#e5e7eb',
    },
    overlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        zIndex: 1000,
    },
    notificationContainer: {
        position: 'absolute',
        bottom: 32,
        left: 24,
        right: 24,
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 18,
        borderWidth: 1,
        borderColor: ACCENT_COLOR,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.12,
        shadowRadius: 8,
        flexDirection: 'row',
        alignItems: 'center',
        zIndex: 1000,
        elevation: 8,
    },
    notificationIcon: {
        marginRight: 12,
    },
    notificationText: {
        fontSize: 16,
        fontWeight: '600',
        color: ACCENT_COLOR,
        textAlign: 'center',
    },
});
